#!/bin/bash -e

if [ "$DEBUG_S2I" == "true" ]; then
    set -x
    env | sort
    ls -la
fi

if [ -f pom.xml ]; then
    echo "Found pom.xml - packaging with maven"
    if [ -f mvnw ]; then
        sh ./mvnw package
    else
        mvn package
    fi
    if [ "$MAIN_JAR" == "" ]; then
        MAIN_JAR=$(find target/ -maxdepth 2 -name "*.jar")
    fi
else
    echo "No pom.xml - exiting"
    exit 1
fi

echo "MAIN_JAR=$MAIN_JAR"

if [ ! -f $MAIN_JAR ]; then
    echo "No $MAIN_JAR - exiting"
    exit 1
fi

mv $MAIN_JAR main.jar

if [ "$DEBUG_S2I" == "true" ]; then
    ls -la
fi
