apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: hello-world-pod
spec:
  containers:
  - env:
    - name: MESSAGE
      value: Hello from a pod
    image: localhost/hello-world:latest
    imagePullPolicy: Always
    name: hello-world
    resources: {}
