FROM openshift/crc-base:latest

EXPOSE 8080
EXPOSE 8443

LABEL io.openshift.expose-services="8080:http,8443:https"

ENV JAVA_VERSION=25
ENV JAVA_HOME=/usr/local/graalvm-jdk-${JAVA_VERSION}

ENV PATH="${PATH}:${JAVA_HOME}/bin"

USER root

COPY ./root /

RUN GRAALVM_TAR=graalvm-jdk-${JAVA_VERSION}_linux-x64_bin.tar.gz && \
    curl -SLO https://download.oracle.com/graalvm/${JAVA_VERSION}/latest/${GRAALVM_TAR} && \
    tar xzf ${GRAALVM_TAR} -C /usr/local && \
    rm ${GRAALVM_TAR} && \
    ln -s $(find /usr/local -name "graalvm-jdk-${JAVA_VERSION}*") ${JAVA_HOME}

USER ${USER_ID}

ENTRYPOINT ["container-entrypoint"]
