apiVersion: template.openshift.io/v1
kind: Template
message: A new java application has been created in your project
metadata:
  annotations:
    iconClass: icon-openjdk
    tags: quickstart,java
  labels:
    template: crc-java11-dual
  name: crc-java11-dual
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: POD_APPLICATION
          value: ${APPLICATION_NAME}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
    source:
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
      dockerfile: |-
        FROM image-registry.openshift-image-registry.svc:5000/openshift/crc-openjdk11-builder:latest as builder

        USER root

        COPY . /tmp/src

        RUN /usr/libexec/s2i/assemble

        FROM image-registry.openshift-image-registry.svc:5000/openshift/crc-openjdk11-runtime:latest as runtime

        COPY --from=builder /tmp/src/target/main.jar /app/main.jar
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env: []
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- name: APPLICATION_NAME
  description: The name for the application.
  displayName: Application Name
  required: true
  value: simple-java-webapi
- name: SOURCE_REPOSITORY_URL
  description: Git source URI for application
  displayName: Git Repository URL
  required: true
  value: https://github.com/mopanowicz/simple-quarkus-webapi.git
- name: SOURCE_REPOSITORY_REF
  description: Git branch/tag reference
  displayName: Git Reference
  value: main
