apiVersion: template.openshift.io/v1
kind: Template
message: A new java application has been created in your project
metadata:
  annotations:
    iconClass: icon-openjdk
    tags: quickstart,java
  labels:
    template: crc-java11-dual
  name: crc-java11-dual
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: POD_APPLICATION
          value: ${APPLICATION_NAME}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
    source:
      git:
        ref: ${SOURCE_GIT_REF}
        uri: ${SOURCE_GIT_URL}
      type: Git
      contextDir: ${SOURCE_CONTEXT_DIR}
      dockerfile: |-
        FROM image-registry.openshift-image-registry.svc:5000/openshift/crc-openjdk11-builder:latest as builder

        USER root

        COPY . /tmp/src

        RUN cd /tmp/src && /usr/libexec/s2i/assemble

        FROM image-registry.openshift-image-registry.svc:5000/openshift/crc-openjdk11-runtime:latest as runtime

        COPY --from=builder /tmp/src/main.jar /app/main.jar
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env: []
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  value: demo-api-spring
  required: true
- name: SOURCE_GIT_URL
  displayName: Source repository URL
  value: https://github.com/mopanowicz/crc.git
  required: true
- name: SOURCE_GIT_REF
  displayName: Source reference
  value: main
- name: SOURCE_CONTEXT_DIR
  displayName: Source context dir
  value: examples/demo-api-spring
- name: MAIN_JAR
  description: Application main jar in case the build process produces more than one jar file
  displayName: Main JAR
