#!/bin/bash

if [ "$DEBUG_S2I" == "true" ]; then
    set -x
    env | sort
    ls -la
fi

if [ "$BUILD_COMMAND" == "" ]; then
    if [ -f pom.xml ]; then
        if [ -f mvnw ]; then
            BUILD_COMMAND="sh ./mvnw package"
        else
            BUILD_COMMAND="mvn package"
        fi
    else
        echo "No pom.xml - exiting"
        exit 1
    fi
fi

echo "BUILD_COMMAND=$BUILD_COMMAND"
$BUILD_COMMAND

if [ "$MAIN_JAR" == "" ]; then
    MAIN_JAR=$(find . -name "*.jar" -maxdepth 2)
fi

echo "MAIN_JAR=$MAIN_JAR"

if [ ! -f $MAIN_JAR ]; then
    echo "No $MAIN_JAR - exiting"
    exit 1
fi

mv $MAIN_JAR main.jar

if [ "$DEBUG_S2I" == "true" ]; then
    ls -la
fi
