CREATE ROLE demospring
    WITH LOGIN NOSUPERUSER CREATEDB NOCREATEROLE INHERIT NOREPLICATION CONNECTION LIMIT -1
    PASSWORD 'demospring123';

CREATE DATABASE demospring
    WITH OWNER=demospring ENCODING = 'UTF8' CONNECTION LIMIT = -1;