#!/usr/bin/env bash

export KAFKA_CLIENT_ROOT=${KAFKA_CLIENT_ROOT:-/opt/kafka}
export BOOTSTRAP_SERVER=${BOOTSTRAP_SERVER:-localhost:9092}

echo "BOOTSTRAP_SERVER=${BOOTSTRAP_SERVER}"
echo "KAFKA_CLIENT_ROOT=${KAFKA_CLIENT_ROOT}"
