apiVersion: template.openshift.io/v1
kind: Template
message: A new java application has been created in your project
metadata:
  annotations:
    iconClass: icon-openjdk
    tags: quickstart,java,java17
  labels:
    template: crc-graaljdk17-dual
  name: crc-graaljdk17-dual
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The application's http port.
      service.alpha.openshift.io/serving-cert-secret-name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/name: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: https
      port: 8443
      targetPort: 8443
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-https
  kind: Route
  metadata:
    annotations:
      description: Route for application's https service
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/name: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    to:
      name: ${APPLICATION_NAME}
    tls:
      termination: reencrypt
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APPLICATION_NAME}-git-secret
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/name: ${APPLICATION_NAME}
  type: kubernetes.io/basic-auth
  stringData:
    password: ${GIT_TOKEN}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/name: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/name: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: POD_APPLICATION
          value: ${APPLICATION_NAME}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
    source:
      git:
        ref: ${SOURCE_GIT_REF}
        uri: ${SOURCE_GIT_URI}
      type: Git
      contextDir: ${SOURCE_CONTEXT_DIR}
      sourceSecret:
        name: ${APPLICATION_NAME}-git-secret
      dockerfile: |-
        FROM ${IMAGE_REGISTRY}/${BUILDER_IMAGE} as builder

        COPY . ${HOME}

        # ENV MAVEN_OPTS="-Dmaven.test.skip=true"

        RUN /usr/libexec/s2i/assemble

        FROM ${IMAGE_REGISTRY}/${RUNTIME_IMAGE}

        LABEL builder.image=${IMAGE_REGISTRY}/${BUILDER_IMAGE}
        LABEL runtime.image=${IMAGE_REGISTRY}/${RUNTIME_IMAGE}

        COPY --from=builder ${HOME}/main.jar ${HOME}/main.jar
      forcePull: true
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.openshift.io/runtime: java
    annotations:
      app.openshift.io/vcs-ref: '${SOURCE_GIT_REF}'
      app.openshift.io/vcs-uri: '${SOURCE_GIT_URI}'
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env: []
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8081
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
          volumeMounts:
          - mountPath: /svc-tls
            name: ${APPLICATION_NAME}-tls
            readonly: true
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${APPLICATION_NAME}-tls
          secret:
            secretName: ${APPLICATION_NAME}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  value: demo-api-spring-graaljdk17
  required: true
- name: SOURCE_GIT_URI
  displayName: Source repository URI
  value: https://github.com/mopanowicz/crc.git
  required: true
- name: SOURCE_GIT_REF
  displayName: Source reference
  value: main
- name: SOURCE_CONTEXT_DIR
  displayName: Source context dir
  value: examples/demo-api-spring
- name: GIT_TOKEN
  displayName: Source repository access token
- name: MAIN_JAR
  description: Application main jar in case the build process produces more than one jar file
  displayName: Main JAR
- name: BUILDER_IMAGE
  displayName: Builder image
  value: crc-graaljdk17-builder:release
  required: true
- name: RUNTIME_IMAGE
  displayName: Runtime image
  value: crc-graaljdk17-runtime:release
  required: true
- name: IMAGE_REGISTRY
  displayName: Image registry
  value: image-registry.openshift-image-registry.svc:5000/openshift
