#!/bin/bash

if [ "$BUILD_COMMAND" == "" ]; then
    if [ -f pom.xml ]; then
        if [ -f mvnw ]; then
            BUILD_COMMAND="sh ./mvnw package"
        else
            BUILD_COMMAND="mvn package"
        fi
    elif [ -f build.gradle ]; then
        if [ -f gradlew ]; then
            BUILD_COMMAND="sh ./gradlew package"
        else
            BUILD_COMMAND="gradle package"
        fi
    else
        echo "Unable to determine the builder - exiting"
        exit 1
    fi
fi

echo "BUILD_COMMAND=$BUILD_COMMAND"

$BUILD_COMMAND

if [ "$MAIN_JAR" == "" ]; then
    MAIN_JAR=$(find . -name "*.jar")
fi

echo "MAIN_JAR=$MAIN_JAR"

if [ ! -f $MAIN_JAR ]; then
    echo "No $MAIN_JAR - exiting"
    exit 1
fi

mv $MAIN_JAR main.jar
