server:
  port: 8084

management:
  endpoints:
    web.exposure.include: "*"
    jmx.exposure.include: "*"

spring:
  data:
    mongodb:
      uri: mongodb://mongo.local/test

test-controller:
  default-sleep-ms: 0
  mongo-on: true
  system-out: true

logging:
  config: classpath:logging.xml
  level:
    root: INFO
    com.example: INFO
  appender:
    name: kafkaAppender
  event:
    labels:
      owner: no_owner
      system: spring-2-kafka-logback
    namespace: ${POD_NAMESPACE:no_namespace}
    pod.name: ${POD_NAME:no_pod_name}
    container.name: ${container:no_container_name}
  kafka:
    topic: logEvents
    service:
      enabled: false
      blocking: true
    # https://kafka.apache.org/documentation/#producerconfigs
    properties:
      bootstrap.servers: kafka.local:9092
      client.id: spring-2-kafka-logback
      security.protocol: PLAINTEXT # PLAINTEXT SSL
      acks: 1
      max.block.ms: 60000 # default: 60000
      buffer.memory: 33554432 # default: 33554432 == 32 * 1024 * 1024
      batch.size: 16384
      compression.type: none
      request.timeout.ms: 6000
      socket.connection.setup.timeout.ms: 2000
      socket.connection.setup.timeout.max.ms: 6000
