CREATE TABLE test (
    id varchar(255) NOT NULL,
    text lvarchar(30000),
    created DATETIME YEAR TO SECOND DEFAULT CURRENT YEAR TO SECOND NOT NULL
);

ALTER TABLE test ADD CONSTRAINT PRIMARY KEY (id);
