#!/usr/bin/env bash

OUTPUT_FILE=${1:-git.properties}

source $(dirname $0)/git-library.sh

{
  echo "# Generated by git-properties.sh"
  echo "git.branch=$(git_branch main)"
  echo "git.build.hostname=$(git_build_hostname)"
  echo "git.build.time=$(git_build_time)"
  echo "git.build.user.name=$(git_build_user_name)"
  echo "git.build.user.email=$(git_build_user_email)"
  echo "git.build.version=$(git_build_version)"
  echo "git.closest.tag.commit.count=$(git_closest_tag_commit_count)"
  echo "git.closest.tag.name=$(git_closest_tag_name)"
  echo "git.commit.author.time=$(git_commit_author_time)"
  echo "git.commit.committer.time=$(git_commit_commiter_time)"
  echo "git.commit.id=$(git_commit_id)"
  echo "git.commit.id.abbrev=$(git_commit_id_short)"
  echo "git.commit.id.describe=$(git_commit_id_describe)"
  echo "git.commit.id.describe-short=$(git_commit_id_describe_short)"
  echo "git.commit.message.full=$(git_commit_message)"
  echo "git.commit.message.short=$(git_commit_message_short)"
  echo "git.commit.time=$(git_commit_time)"
  echo "git.commit.user.email=$(git_commit_user_email)"
  echo "git.commit.user.name=$(git_commit_user_name)"
  echo "git.dirty=$(git_is_dirty)"
  echo "git.local.branch.ahead=$(git_local_branch_ahead_of_remote)"
  echo "git.local.branch.behind=$(git_local_branch_behind_remote)"
  echo "git.remote.origin.url=$(git_remote_url)"
  echo "git.tag=$(git_closest_tag_name)"
  echo "git.tags=$(git_closest_tag_name)"
  echo "git.total.commit.count=$(git_total_commit_count)"
} > $OUTPUT_FILE
