server:
  port: 8443
  servlet.context-path: /
  ssl:
    enabled: true
    key-store: ${KEYSTORE}
    key-store-password: ${KEYSTORE_PASSWORD:changeit}

spring:
  jpa.open-in-view: false
  datasource:
    url: spring.datasource.url=jdbc:h2:mem:test;
    username: sa
    password:

logging:
  level:
    root: INFO
    com.example: DEBUG

---
spring.config.activate.on-profile: dev

server:
  port: 8081
  ssl.enabled: false
