apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    iconClass: icon-java
    tags: quickstart,kafka,kafka_connect
  labels:
    template: crc-kafka-connect-runtime-openjdk17
  name: crc-kafka-connect-runtime-openjdk17
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APPLICATION_NAME}-git-secret
    labels:
      app: ${APPLICATION_NAME}
  type: kubernetes.io/basic-auth
  stringData:
    password: ${GIT_TOKEN}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    completionDeadlineSeconds: 1800
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: POD_APPLICATION
          value: ${APPLICATION_NAME}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BUILD_ARGS
          value: '-q'
      forcePull: true
    source:
      git:
        ref: ${SOURCE_GIT_REF}
        uri: ${SOURCE_GIT_URI}
      type: Git
      contextDir: ${SOURCE_CONTEXT_DIR}
      sourceSecret:
        name: ${APPLICATION_NAME}-git-secret
      dockerfile: |-
        FROM ${IMAGE_REGISTRY}/${BUILDER_IMAGE} as builder

        COPY . ${HOME}

        RUN /usr/libexec/s2i/assemble

        FROM ${IMAGE_REGISTRY}/${RUNTIME_IMAGE}

        LABEL builder.image=${IMAGE_REGISTRY}/${BUILDER_IMAGE}
        LABEL runtime.image=${IMAGE_REGISTRY}/${RUNTIME_IMAGE}

        COPY --from=builder ${HOME}/target/InsertUuid-1.0-SNAPSHOT.jar ${KAFKA_CONNECT_PLUGIN_PATH}/InsertUuid-1.0-SNAPSHOT.jar

        COPY --from=builder /examples/connect-distributed.properties ${KAFKA_CONNECT_CONFIG_PATH}/connect-distributed.properties
      forcePull: true
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      deployment: ${APPLICATION_NAME}
    annotations:
      app.openshift.io/vcs-ref: '${SOURCE_GIT_REF}'
      app.openshift.io/vcs-uri: '${SOURCE_GIT_URI}'
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          deployment: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env: []
          image: ${APPLICATION_IMAGE}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8081
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
          volumeMounts:
          - mountPath: /svc-tls
            name: ${APPLICATION_NAME}-tls
            readonly: true
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${APPLICATION_NAME}-tls
          secret:
            secretName: ${APPLICATION_NAME}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: ${APPLICATION_NAME}
    creationTimestamp: null
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8083
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8083
    selector:
      deployment: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  id: ${APPLICATION_NAME}-https
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    to:
      kind: Service
      name: ${APPLICATION_NAME}
    port:
      targetPort: https
    tls:
      termination: edge
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  value: kafka-connect
  required: true
- name: SOURCE_GIT_URI
  displayName: Source repository URI
  value: https://github.com/mopanowicz/crc.git
  required: true
- name: SOURCE_GIT_REF
  displayName: Source reference
  value: main
- name: SOURCE_CONTEXT_DIR
  displayName: Source context dir
  value: examples/cloned/kafka-connect-insert-uuid
- name: GIT_TOKEN
  displayName: Source repository access token
- name: MAIN_JAR
  description: Application main jar in case the build process produces more than one jar file
  displayName: Main JAR
- name: BUILDER_IMAGE
  displayName: Builder image
  value: crc-openjdk17-builder:release
  required: true
- name: RUNTIME_IMAGE
  displayName: Runtime image
  value: crc-kafka-connect-runtime-openjdk17:release
  required: true
- name: IMAGE_REGISTRY
  displayName: Image registry
  value: image-registry.openshift-image-registry.svc:5000/openshift
- description: Image to deploy (REPLACE APPLICATION_NAME with proper image name)
  name: APPLICATION_IMAGE
  value: image-registry.openshift-image-registry.svc:5000/NAMESPACE/kafka-connect
  required: true
